### ISSUE TITLE
2 small changes to make the lib installer-ready

### ISSUE THREAD

**Issue by microelly2** [yorikvanhavre/FreeCAD-symbols#1]
I have added it to my plugin installer:

 https://github.com/microelly2/freecad-pluginloader/commit/758288b8164f835fac3948105c2c365524f187ab#diff-59364468d8b293a5b109d323ac7f7e40

two things should be changed

configuration can be done with my plugininstaller if you insert this piece of code ...

LIBRARYPATH = "/home/yorik/Sources/FreeCAD-symbols"

automated configuration

s=FreeCAD.ParamGet('User parameter:Plugins/symbollib').GetString('destination')
if s<>'':
	LIBRARYPATH = s

* LIBRARYPATH should be used as local parameter line #118

 m.addDockWidget(QtCore.Qt.RightDockWidgetArea,ExpDockWidget(LIBRARYPATH))

and line #62
    def __init__(self,LIBRARYPATH):
  
these changes should not restrict the common use ot the symbollib but enable it to be managed by the plugin installer.

**Comment by yorikvanhavre** [comment]
Cool! I just gave you write permission to the repo.
